import type { StarterRule } from "./ruleTypes";

// Starter detection rules. Every pattern here matches *indicators* of an attack technique
// (payload syntax, scanner fingerprints, known-sensitive paths) inside data that's already
// been logged - nothing here sends, replays, or constructs an attack; it's read-only regex
// matching over request paths/user-agents/evidence text already sitting in SecurityEvents.
//
// This file is the canonical source for the starter rule set - `npm run migrate:intrusion-
// detection` seeds these into SecurityDetectionRules. After that, the DB row is what the
// rule engine actually reads (so an admin can disable/retune a rule via the future rule-
// management API without a redeploy); re-running the migration only inserts rules that
// don't already exist by RuleKey, it never overwrites an admin's changes to an existing row.
export const STARTER_RULES: StarterRule[] = [
  // --- Injection & payload patterns -----------------------------------------------------
  {
    ruleKey: "sqli-pattern",
    name: "SQL injection pattern in request",
    description: "The request path/query contains syntax commonly used in SQL injection probing (UNION SELECT, boolean tautologies, comment terminators, stacked queries).",
    category: "sql_injection",
    severity: "high",
    confidence: 70,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: [
        "(?:\\bunion\\b(?:\\s|%20|/\\*.*?\\*/)+\\bselect\\b)",
        "(?:\\bor\\b|\\band\\b)\\s+['\"]?\\s*\\d+\\s*=\\s*\\d+",
        "(?:'|%27)\\s*(?:or|and)\\s",
        "(?:-{2}|#|%23)\\s*$",
        "\\bexec(?:\\s|\\+)+(?:s|x)p_\\w+",
        "\\bsleep\\s*\\(\\s*\\d+\\s*\\)",
        "\\bwaitfor\\s+delay\\b",
        "\\binformation_schema\\b",
      ],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp", "injection"],
    recommendedAction: "Review the request; if confirmed malicious, add the source IP to the blocklist and check application logs for a successful injection.",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection"],
  },
  {
    ruleKey: "xss-pattern",
    name: "Cross-site scripting pattern in request",
    description: "The request contains an inline script tag, javascript: URI, or an on-event-handler attribute - common XSS injection syntax.",
    category: "xss",
    severity: "high",
    confidence: 65,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: [
        "<script[\\s>]",
        "javascript\\s*:",
        "on(?:error|load|click|mouseover|focus)\\s*=",
        "<img[^>]+src\\s*=\\s*[\"']?\\s*javascript:",
        "%3Cscript",
        "document\\.cookie",
      ],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp", "injection"],
    recommendedAction: "Confirm whether the payload reached a reflected/stored context; if so, patch the vulnerable endpoint and rotate any exposed session cookies.",
    references: ["https://owasp.org/www-community/attacks/xss/"],
  },
  {
    ruleKey: "path-traversal-pattern",
    name: "Path traversal pattern in request",
    description: "The request path contains directory-traversal sequences (../, encoded variants) that attempt to escape the intended web root.",
    category: "path_traversal",
    severity: "high",
    confidence: 75,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["\\.\\./", "\\.\\.\\\\", "%2e%2e%2f", "%2e%2e/", "\\.\\.%2f", "%252e%252e"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp"],
    recommendedAction: "Verify the request didn't reach a filesystem read - check for unauthorized file access in application logs.",
    references: ["https://owasp.org/www-community/attacks/Path_Traversal"],
  },
  {
    ruleKey: "lfi-rfi-pattern",
    name: "Local/remote file inclusion pattern",
    description: "The request references a wrapper scheme (php://, data://) or a well-known sensitive local file (/etc/passwd, boot.ini) - typical LFI/RFI probing.",
    category: "lfi_rfi",
    severity: "critical",
    confidence: 75,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["(?:php|data|zip|expect|phar)://", "/etc/passwd", "boot\\.ini", "win\\.ini", "include(?:\\?|=)[^&]*https?://"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp"],
    recommendedAction: "Treat as high priority - LFI/RFI can lead to remote code execution. Check whether the file was actually included/executed.",
    references: ["https://owasp.org/www-community/vulnerabilities/File_inclusion"],
  },
  {
    ruleKey: "command-injection-pattern",
    name: "OS command injection pattern",
    description: "The request contains shell metacharacters chained with a common command name (cat, whoami, wget, nc) - a typical command-injection probe.",
    category: "command_injection",
    severity: "critical",
    confidence: 70,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: [
        ";\\s*(?:cat|ls|whoami|id|uname|wget|curl|nc|netcat)\\b",
        "\\|\\s*(?:nc|netcat|bash|sh|powershell)\\b",
        "`[^`]+`",
        "\\$\\([^)]+\\)",
        "&&\\s*(?:cat|ls|whoami|dir|type)\\b",
      ],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp"],
    recommendedAction: "Critical - check for signs of successful command execution (unexpected processes, new files, outbound connections) on the target host.",
    references: ["https://owasp.org/www-community/attacks/Command_Injection"],
  },
  {
    ruleKey: "ssrf-pattern",
    name: "Server-side request forgery indicator",
    description: "The request targets an internal/loopback address or a cloud metadata endpoint in a parameter value - a classic SSRF probe.",
    category: "ssrf",
    severity: "high",
    confidence: 60,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["169\\.254\\.169\\.254", "metadata\\.google\\.internal", "(?:https?://|=)(?:localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)(?::\\d+)?"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp"],
    recommendedAction: "Check whether the application fetches the attacker-supplied URL server-side; if so, this can expose internal services or cloud credentials.",
    references: ["https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"],
  },
  {
    ruleKey: "xxe-pattern",
    name: "XML external entity indicator",
    description: "Request text contains a DOCTYPE/ENTITY declaration with a SYSTEM file/URL reference - typical XXE payload structure.",
    category: "xxe",
    severity: "high",
    confidence: 65,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "evidenceSummary",
      patterns: ["<!DOCTYPE[^>]+ENTITY", "<!ENTITY[^>]+SYSTEM"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["owasp"],
    recommendedAction: "Confirm the XML parser has external entity resolution disabled; XXE can lead to local file disclosure or SSRF.",
    references: ["https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing"],
  },

  // --- Reconnaissance / scanner / bot signatures -----------------------------------------
  {
    ruleKey: "scanner-user-agent",
    name: "Known vulnerability scanner user agent",
    description: "The User-Agent header identifies a well-known automated scanning tool (sqlmap, nikto, nmap, Acunetix, Nessus, Burp Suite, etc.).",
    category: "scanner_signature",
    severity: "medium",
    confidence: 85,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "userAgent",
      patterns: ["sqlmap", "nikto", "nmap", "acunetix", "nessus", "burpsuite", "w3af", "havij", "dirbuster", "masscan", "zgrab", "gobuster", "wpscan", "metasploit"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Low urgency if from an authorized internal scanner/pentest; otherwise consider a temporary block while investigating scope.",
    references: [],
  },
  {
    ruleKey: "automated-bot-user-agent",
    name: "Automated script/bot user agent",
    description: "The User-Agent identifies a generic HTTP client library (curl, python-requests, Go-http-client, Scrapy) rather than a browser - common for scripted/bot traffic.",
    category: "bot_activity",
    severity: "low",
    confidence: 40,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "userAgent",
      patterns: ["python-requests", "^curl/", "libwww-perl", "go-http-client", "^Scrapy/", "^Java/\\d", "^okhttp"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Low confidence alone - correlate with request rate/target paths before acting. Legitimate integrations also use these clients.",
    references: [],
  },

  // --- Sensitive path / file targeting ---------------------------------------------------
  {
    ruleKey: "sensitive-file-access",
    name: "Request targeting a sensitive file",
    description: "The request targets a file that should never be publicly served (private keys, .env, VCS metadata, credential stores).",
    category: "sensitive_file_access",
    severity: "high",
    confidence: 80,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["\\.env(?:\\.|$)", "/\\.git/", "/\\.svn/", "id_rsa", "\\.pem$", "\\.key$", "wp-config\\.php", "web\\.config$", "\\.htpasswd$"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["recon"],
    recommendedAction: "Confirm the file is not actually publicly accessible (HTTP 200); if it is, remove/block it immediately and rotate any exposed secrets.",
    references: [],
  },
  {
    ruleKey: "admin-path-probe",
    name: "Request targeting an administrative path",
    description: "The request targets a common admin/management console path (wp-admin, phpMyAdmin, Adminer, Tomcat manager).",
    category: "admin_path_access",
    severity: "medium",
    confidence: 55,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["/wp-admin", "/wp-login\\.php", "/administrator/", "/phpmyadmin", "/pma/", "/adminer\\.php", "/manager/html", "/solr/admin"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Expected if the site legitimately runs that admin panel - verify the requester is authorized, otherwise monitor for follow-up brute-force attempts.",
    references: [],
  },
  {
    ruleKey: "backup-config-exposure",
    name: "Request targeting a backup or config export file",
    description: "The request targets a backup archive, database dump, or config-management file (.bak, .sql, .zip, docker-compose.yml) that may leak credentials or source code.",
    category: "backup_config_exposure",
    severity: "high",
    confidence: 65,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["\\.(?:bak|old|backup|orig|save)$", "\\.sql(?:\\.gz)?$", "\\.zip$", "\\.tar\\.gz$", "docker-compose\\.ya?ml$", "\\.git/config$"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["recon"],
    recommendedAction: "If the file returned HTTP 200, remove it from the web root immediately and treat any credentials/source it contained as compromised.",
    references: [],
  },
  {
    ruleKey: "suspicious-upload-path",
    name: "POST to an executable-looking path",
    description: "A POST request targets a path with a server-executable extension (.php, .jsp, .aspx) - could be a legitimate upload handler, or a webshell drop attempt if the path is unexpected.",
    category: "suspicious_upload",
    severity: "medium",
    confidence: 45,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["\\.(?:php\\d?|jsp|jspx|asp|aspx|exe|sh|phtml)$"],
      fieldMatches: [{ field: "requestMethod", operator: "equals", value: "POST" }],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["recon"],
    recommendedAction: "Confirm this is an expected upload endpoint for this application; if not, investigate for a webshell drop.",
    references: [],
  },
  {
    ruleKey: "unexpected-http-method",
    name: "Unexpected/rare HTTP method",
    description: "The request used an HTTP method rarely used by legitimate clients (TRACE, TRACK, CONNECT, PROPFIND, DEBUG).",
    category: "unexpected_http_method",
    severity: "low",
    confidence: 50,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestMethod",
      patterns: ["^TRACE$", "^TRACK$", "^CONNECT$", "^PROPFIND$", "^DEBUG$"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Confirm the web server/application doesn't need to support this method; disable it at the server level if not.",
    references: [],
  },
  {
    ruleKey: "unusual-encoding",
    name: "Unusual or double URL encoding",
    description: "The request path contains double-encoded or null-byte sequences, often used to evade WAF pattern matching.",
    category: "unusual_encoding",
    severity: "medium",
    confidence: 55,
    dataSource: "any",
    conditions: {
      type: "pattern",
      dataSource: "any",
      patternField: "requestPath",
      patterns: ["%25(?:2e|2f|5c|00|3c|3e)", "%00", "%c0%ae"],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["evasion"],
    recommendedAction: "Combine with other findings for this IP - double-encoding alone is a weak signal but often accompanies a real payload.",
    references: [],
  },

  // --- Authentication abuse (rate-based) --------------------------------------------------
  {
    ruleKey: "brute-force-login",
    name: "Brute-force login attempts",
    description: "5 or more failed login attempts from the same IP within 5 minutes.",
    category: "brute_force",
    severity: "high",
    confidence: 75,
    dataSource: "admin_audit_log",
    conditions: {
      type: "rate",
      dataSource: "admin_audit_log",
      fieldMatches: [{ field: "fields.success", operator: "equals", value: false }],
      groupBy: "sourceIp",
    },
    thresholdCount: 5,
    thresholdWindowSeconds: 300,
    cooldownSeconds: 600,
    tags: ["auth"],
    recommendedAction: "If confirmed malicious, temporarily block the source IP and confirm the targeted account(s) weren't compromised.",
    references: ["https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks"],
  },
  {
    ruleKey: "credential-stuffing",
    name: "Sustained high-volume login failures (possible credential stuffing)",
    description: "15 or more failed login attempts from the same IP within 10 minutes - well beyond a normal typo/retry pattern.",
    category: "credential_stuffing",
    severity: "critical",
    confidence: 80,
    dataSource: "admin_audit_log",
    conditions: {
      type: "rate",
      dataSource: "admin_audit_log",
      fieldMatches: [{ field: "fields.success", operator: "equals", value: false }],
      groupBy: "sourceIp",
    },
    thresholdCount: 15,
    thresholdWindowSeconds: 600,
    cooldownSeconds: 900,
    tags: ["auth"],
    recommendedAction: "High priority - block the source IP and force a password reset for any accounts it targeted successfully.",
    references: ["https://owasp.org/www-community/attacks/Credential_stuffing"],
  },
  {
    ruleKey: "excessive-auth-failures-sustained",
    name: "Excessive failed authentication over an extended window",
    description: "25 or more failed login attempts from the same IP within an hour - persistent low-and-slow authentication abuse that a tight brute-force window would miss.",
    category: "excessive_auth_failures",
    severity: "medium",
    confidence: 60,
    dataSource: "admin_audit_log",
    conditions: {
      type: "rate",
      dataSource: "admin_audit_log",
      fieldMatches: [{ field: "fields.success", operator: "equals", value: false }],
      groupBy: "sourceIp",
    },
    thresholdCount: 25,
    thresholdWindowSeconds: 3600,
    cooldownSeconds: 3600,
    tags: ["auth"],
    recommendedAction: "Review whether this is a slow, deliberate brute-force attempt designed to stay under rate-limit thresholds.",
    references: [],
  },

  // --- Response-code / request-rate abuse (rate-based) ------------------------------------
  {
    ruleKey: "repeated-404",
    name: "Repeated 404 responses (enumeration)",
    description: "20 or more 404 responses to the same source IP within 60 seconds - typical of directory/file enumeration.",
    category: "repeated_error_responses",
    severity: "medium",
    confidence: 55,
    dataSource: "any",
    conditions: {
      type: "rate",
      dataSource: "any",
      fieldMatches: [{ field: "responseStatus", operator: "equals", value: 404 }],
      groupBy: "sourceIp",
    },
    thresholdCount: 20,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Correlate with requested paths for this IP to see what's being enumerated.",
    references: [],
  },
  {
    ruleKey: "repeated-401-403",
    name: "Repeated 401/403 responses",
    description: "10 or more unauthorized/forbidden responses to the same source IP within 60 seconds - possible access-control probing.",
    category: "repeated_error_responses",
    severity: "medium",
    confidence: 55,
    dataSource: "any",
    conditions: {
      type: "rate",
      dataSource: "any",
      fieldMatches: [{ field: "responseStatus", operator: "in", value: [401, 403] }],
      groupBy: "sourceIp",
    },
    thresholdCount: 10,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Check which resources are being probed and whether any eventually returned 200.",
    references: [],
  },
  {
    ruleKey: "repeated-500",
    name: "Repeated server errors from one source",
    description: "10 or more 500 responses to the same source IP within 60 seconds - can indicate fuzzing/injection attempts crashing request handlers.",
    category: "repeated_error_responses",
    severity: "medium",
    confidence: 50,
    dataSource: "any",
    conditions: {
      type: "rate",
      dataSource: "any",
      fieldMatches: [{ field: "responseStatus", operator: "equals", value: 500 }],
      groupBy: "sourceIp",
    },
    thresholdCount: 10,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Check application error logs for the specific inputs that triggered these errors.",
    references: [],
  },
  {
    ruleKey: "repeated-429",
    name: "Repeatedly hitting rate limits",
    description: "5 or more 429 (Too Many Requests) responses to the same source IP within 60 seconds.",
    category: "repeated_error_responses",
    severity: "low",
    confidence: 50,
    dataSource: "any",
    conditions: {
      type: "rate",
      dataSource: "any",
      fieldMatches: [{ field: "responseStatus", operator: "equals", value: 429 }],
      groupBy: "sourceIp",
    },
    thresholdCount: 5,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 600,
    tags: ["recon"],
    recommendedAction: "Existing rate limiting is working as intended - monitor for continued attempts or a shift to a different source IP.",
    references: [],
  },
  {
    ruleKey: "high-request-rate",
    name: "Abnormally high request rate from one source",
    description: "100 or more requests from the same source IP within 60 seconds - well above typical single-user browsing.",
    category: "high_request_rate",
    severity: "medium",
    confidence: 50,
    dataSource: "any",
    conditions: {
      type: "rate",
      dataSource: "any",
      groupBy: "sourceIp",
    },
    thresholdCount: 100,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["recon"],
    recommendedAction: "Correlate with user agent and target paths - could be a legitimate crawler, a scraper, or a DoS-adjacent scan.",
    references: [],
  },

  // --- Bridging existing Sophos signal into the IDS ---------------------------------------
  {
    ruleKey: "sophos-high-severity-threat",
    name: "High-severity Sophos IPS/Firewall threat event",
    description: "The Sophos firewall itself classified this event as high or critical severity (IPS signature match, ATP detection, etc.).",
    category: "other",
    severity: "high",
    confidence: 85,
    dataSource: "sophos_threat",
    conditions: {
      // No regex needed - Sophos already did the classification. A pattern-type rule with
      // fieldMatches and no `patterns` array matches purely on the field check below.
      type: "pattern",
      dataSource: "sophos_threat",
      fieldMatches: [{ field: "fields.severity", operator: "in", value: ["Critical", "High", "critical", "high"] }],
    },
    thresholdCount: 1,
    thresholdWindowSeconds: 60,
    cooldownSeconds: 300,
    tags: ["sophos"],
    recommendedAction: "Review the underlying Sophos threat log entry for full detail; this alert exists to surface it in the unified IDS dashboard alongside web-app-layer findings.",
    references: [],
  },
];
