import type { Confidence, ScoreModule } from "./types";

// Stable, well-known reference URLs only — no guessed cheat-sheet slugs. CWE's own URL
// scheme (cwe.mitre.org/data/definitions/{id}.html) is documented and stable, so it's safe
// to build per numeric id rather than needing to look each one up individually.
const OWASP_TOP10 = "https://owasp.org/Top10/";
const OWASP_WSTG = "https://owasp.org/www-project-web-security-testing-guide/";
const CVSS_SPEC = "https://www.first.org/cvss/v3-1/specification-document";
const CIS_CONTROLS = "https://www.cisecurity.org/controls";
// Short "CWE-N" id string — this is what's persisted in the DB's Cwe NVARCHAR(20) column.
const cweId = (id: number) => `CWE-${id}`;
// Full reference URL — belongs only in the references[] list, never in the short cwe field
// (a URL there would overflow/truncate the 20-char column, the same class of bug already
// fixed once this session for MaskedEvidence).
const cweUrl = (id: number) => `https://cwe.mitre.org/data/definitions/${id}.html`;

export interface CatalogEntry {
  cvss: number;
  cwe: string;
  owaspCategory: string;
  module: ScoreModule;
  defaultConfidence: Confidence;
  businessImpact: string;
  attackScenario: string;
  verificationSteps: string;
  references: string[];
}

// Fixed, per-category CVSS v3.1 base scores (industry-typical scores for that vulnerability
// class) rather than a dynamic per-instance calculator — see CVSS_SPEC. Every category this
// scanner can actually raise gets an entry; categories with no realistic passive/safe signal
// still get one so the report can render an honest "no indicators observed" line instead of
// omitting the OWASP category entirely.
export const FINDING_CATALOG: Record<string, CatalogEntry> = {
  missing_headers: {
    cvss: 4.3,
    cwe: cweId(693),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "headers",
    defaultConfidence: "Confirmed",
    businessImpact: "Missing browser security headers weaken the site's built-in defenses against XSS, clickjacking, and data-leakage in a compromised or malicious sub-resource.",
    attackScenario: "An attacker who can inject any content (a compromised ad/script, a reflected parameter) has fewer browser-side restrictions to work around.",
    verificationSteps: "Request the page and inspect response headers directly (curl -I or browser devtools Network tab).",
    references: [OWASP_TOP10, cweUrl(693)],
  },
  insecure_cookies: {
    cvss: 5.4,
    cwe: cweId(614),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "cookies",
    defaultConfidence: "Confirmed",
    businessImpact: "Cookies without Secure/HttpOnly/SameSite are easier to steal via network interception or script injection, potentially leading to session hijacking.",
    attackScenario: "On a shared or compromised network, a cookie sent without Secure can be captured in plaintext; without HttpOnly it's readable by any injected script.",
    verificationSteps: "Inspect the Set-Cookie header on the response for the Secure, HttpOnly, and SameSite attributes.",
    references: [cweUrl(614), OWASP_WSTG],
  },
  cors_misconfiguration: {
    cvss: 7.1,
    cwe: cweId(942),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "headers",
    defaultConfidence: "Firm",
    businessImpact: "An overly permissive CORS policy lets other origins read authenticated responses, which can leak session-bound data cross-site.",
    attackScenario: "A malicious page in a victim's browser issues a credentialed cross-origin request and reads the response because the server allows any/reflected origin with credentials.",
    verificationSteps: "Send a request with an unrecognized Origin header and confirm whether Access-Control-Allow-Origin reflects it or returns *.",
    references: [cweUrl(942), OWASP_TOP10],
  },
  insecure_http_methods: {
    cvss: 5.3,
    cwe: cweId(650),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "Enabled methods like TRACE, PUT, or DELETE expand the attack surface beyond what the application needs.",
    attackScenario: "TRACE can assist in Cross-Site Tracing attacks against HttpOnly cookies; an exposed PUT/DELETE could allow unintended writes if access control is also weak.",
    verificationSteps: "Send an OPTIONS request and inspect the Allow header; optionally send a real TRACE/PUT/DELETE to a safe path and confirm it's rejected.",
    references: [cweUrl(650), OWASP_WSTG],
  },
  missing_https_redirect: {
    cvss: 5.9,
    cwe: cweId(319),
    owaspCategory: "A02:2021 – Cryptographic Failures",
    module: "ssl",
    defaultConfidence: "Confirmed",
    businessImpact: "Visitors who type or follow a plain http:// link stay unencrypted until/unless something else redirects them, exposing traffic to interception.",
    attackScenario: "An attacker on the same network (public Wi-Fi, compromised router) intercepts the initial plaintext request before any redirect occurs.",
    verificationSteps: "Request the http:// version of the site directly and confirm the response is a 3xx redirect to https://.",
    references: [cweUrl(319), OWASP_TOP10],
  },
  mixed_content: {
    cvss: 4.8,
    cwe: cweId(319),
    owaspCategory: "A02:2021 – Cryptographic Failures",
    module: "ssl",
    defaultConfidence: "Confirmed",
    businessImpact: "HTTP sub-resources loaded on an HTTPS page can be intercepted or tampered with, undermining the page's own encryption.",
    attackScenario: "A network attacker replaces an insecurely-loaded script/image with a malicious version, since it isn't protected by TLS.",
    verificationSteps: "Load the page over HTTPS and check the browser console / response HTML for http:// resource references.",
    references: [cweUrl(319)],
  },
  exposed_sensitive_files: {
    cvss: 7.5,
    cwe: cweId(538),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "Publicly reachable configuration/backup/credential files can leak secrets, source code, or database contents.",
    attackScenario: "An attacker requests a known sensitive path directly (no authentication needed) and downloads it if the server returns it.",
    verificationSteps: "Request the specific path directly and confirm the HTTP status code and content-type of the response.",
    references: [cweUrl(538), OWASP_TOP10],
  },
  exposed_package_manifest: {
    cvss: 5.3,
    cwe: cweId(200),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "js",
    defaultConfidence: "Confirmed",
    businessImpact: "A publicly exposed dependency manifest reveals your exact technology stack and package versions, making it trivial to look up known vulnerabilities.",
    attackScenario: "An attacker downloads the manifest directly, cross-references every listed package+version against public CVE databases, and targets any match.",
    verificationSteps: "Request the file path directly and confirm it returns the manifest's actual content.",
    references: [cweUrl(200), OWASP_TOP10],
  },
  exposed_admin_api: {
    cvss: 3.1,
    cwe: cweId(284),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "server",
    defaultConfidence: "Tentative",
    businessImpact: "Publicly reachable admin/API paths may be intentional, but widen the attack surface if not properly access-controlled.",
    attackScenario: "An attacker enumerates common admin/API paths looking for one that's reachable and under-protected.",
    verificationSteps: "Request the path directly and confirm whether it requires authentication before returning meaningful content.",
    references: [OWASP_WSTG],
  },
  debug_exposure: {
    cvss: 6.5,
    cwe: cweId(209),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "Verbose error pages/stack traces can reveal framework versions, file paths, and internal logic that help an attacker plan further attacks.",
    attackScenario: "An attacker triggers an error (even accidentally) and reads the stack trace to learn the technology stack and internal file layout.",
    verificationSteps: "Trigger the same condition and confirm whether the response includes a stack trace or framework debug page.",
    references: [cweUrl(209), OWASP_TOP10],
  },
  open_redirect_risk: {
    cvss: 4.7,
    cwe: cweId(601),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Open redirects are commonly abused in phishing to make a malicious link appear to originate from a trusted domain.",
    attackScenario: "An attacker crafts a link to the trusted site's own redirect parameter, pointing the final hop at a phishing page.",
    verificationSteps: "Request the URL with the redirect parameter set to an external test URL and inspect the Location header without following it.",
    references: [cweUrl(601), OWASP_TOP10],
  },
  weak_tls: {
    cvss: 7.4,
    cwe: cweId(326),
    owaspCategory: "A02:2021 – Cryptographic Failures",
    module: "ssl",
    defaultConfidence: "Confirmed",
    businessImpact: "Outdated TLS versions, weak ciphers, or certificate problems reduce or defeat the confidentiality/integrity protection HTTPS is meant to provide.",
    attackScenario: "An attacker capable of network interception downgrades or exploits weak cryptography to read or tamper with traffic.",
    verificationSteps: "Connect with an explicit TLS version/cipher and confirm the server's negotiated protocol, cipher, and certificate details.",
    references: [cweUrl(326), CVSS_SPEC],
  },
  hardcoded_secret: {
    cvss: 9.1,
    cwe: cweId(798),
    owaspCategory: "A07:2021 – Identification and Authentication Failures",
    module: "js",
    defaultConfidence: "Firm",
    businessImpact: "A hardcoded credential or key gives anyone who reads the source/bundle direct access to whatever system it authenticates to.",
    attackScenario: "An attacker downloads a public JS bundle or reads a pasted source snippet and extracts a live credential to use directly.",
    verificationSteps: "Locate the matched pattern in the source/bundle at the given location; rotate the credential regardless of whether it's still valid.",
    references: [cweUrl(798), OWASP_TOP10],
  },
  dangerous_function: {
    cvss: 6.1,
    cwe: cweId(79),
    owaspCategory: "A03:2021 – Injection",
    module: "js",
    defaultConfidence: "Tentative",
    businessImpact: "Use of eval/innerHTML/string-built SQL/shell-exec with dynamic input is a common root cause of injection and XSS vulnerabilities.",
    attackScenario: "An attacker supplies input that reaches the dangerous sink unsanitized, achieving script execution, SQL injection, or command execution depending on the sink.",
    verificationSteps: "Review the matched code location and confirm whether the value passed to the sink can be influenced by user/external input.",
    references: [cweUrl(79), cweUrl(78), OWASP_TOP10],
  },
  http_headers_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "headers",
    defaultConfidence: "Firm",
    businessImpact: "Informational — raw header values captured for the report, not a weakness by itself.",
    attackScenario: "N/A",
    verificationSteps: "Inspect response headers directly.",
    references: [],
  },
  tls_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "ssl",
    defaultConfidence: "Firm",
    businessImpact: "Informational — TLS configuration inventory, not a weakness by itself.",
    attackScenario: "N/A",
    verificationSteps: "Connect with an explicit TLS client and inspect the negotiated parameters.",
    references: [],
  },
  tech_stack_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational — technology inventory, not a weakness by itself.",
    attackScenario: "N/A",
    verificationSteps: "Inspect page source and response headers.",
    references: [],
  },
  scan_error: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Tentative",
    businessImpact: "None directly — this indicates the scanner itself could not complete a check, not a vulnerability.",
    attackScenario: "N/A",
    verificationSteps: "Re-run the scan; if it recurs, check the target site's reachability and the scanner's network path.",
    references: [],
  },

  // Website Information
  website_info_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational asset/inventory data.",
    attackScenario: "N/A",
    verificationSteps: "Cross-check against DNS and a direct browser request.",
    references: [],
  },
  cdn_waf_detected: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational — presence of a CDN/WAF is a positive control, not a weakness.",
    attackScenario: "N/A",
    verificationSteps: "Inspect response headers for the vendor's known fingerprint.",
    references: [],
  },
  hosting_info: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational asset/inventory data.",
    attackScenario: "N/A",
    verificationSteps: "Cross-check the IP/ASN against a public WHOIS/IP-info lookup.",
    references: [],
  },
  missing_security_txt: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "Without security.txt, security researchers have no standard way to responsibly report a vulnerability they find.",
    attackScenario: "N/A — this is a process gap, not an exploitable weakness.",
    verificationSteps: "Request /.well-known/security.txt and confirm whether it exists.",
    references: ["https://www.rfc-editor.org/rfc/rfc9116"],
  },

  // DNS
  dns_records_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "dns",
    defaultConfidence: "Firm",
    businessImpact: "Informational — DNS record inventory, not a weakness.",
    attackScenario: "N/A",
    verificationSteps: "Query the domain's records directly with dig/nslookup.",
    references: [],
  },
  dns_missing_caa: {
    cvss: 2.6,
    cwe: cweId(295),
    owaspCategory: "A02:2021 – Cryptographic Failures",
    module: "dns",
    defaultConfidence: "Confirmed",
    businessImpact: "Without a CAA record, any publicly trusted CA can issue a certificate for this domain, widening the mis-issuance attack surface.",
    attackScenario: "An attacker who compromises a CA's issuance process (or exploits a lax CA) obtains a certificate for this domain.",
    verificationSteps: "Query the domain's CAA record and confirm whether it restricts issuance to specific CAs.",
    references: [cweUrl(295), "https://www.rfc-editor.org/rfc/rfc8659"],
  },
  dns_no_dnssec: {
    cvss: 3.7,
    cwe: cweId(345),
    owaspCategory: "A08:2021 – Software and Data Integrity Failures",
    module: "dns",
    defaultConfidence: "Tentative",
    businessImpact: "Without DNSSEC, DNS responses for this domain aren't cryptographically signed, making cache-poisoning/spoofing attacks (though non-trivial) undetectable to resolvers.",
    attackScenario: "An attacker capable of DNS spoofing/cache poisoning redirects visitors to a malicious server without any signature mismatch being detectable.",
    verificationSteps: "Query for a DNSKEY/DS record on the domain and confirm whether one is published (this checks presence only, not full chain validation).",
    references: [cweUrl(345), CIS_CONTROLS],
  },

  // Email security
  email_records_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Firm",
    businessImpact: "Informational — confirms a positive email-authentication record was found.",
    attackScenario: "N/A",
    verificationSteps: "Query the relevant TXT record directly.",
    references: [],
  },
  email_spf_missing: {
    cvss: 5.3,
    cwe: cweId(290),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Confirmed",
    businessImpact: "Without SPF, receiving mail servers have no way to verify that mail claiming to be from this domain was actually sent by an authorized server, aiding spoofing/phishing.",
    attackScenario: "An attacker sends phishing email that appears to come from this domain; without SPF, the receiving server can't reject it on that basis alone.",
    verificationSteps: "Query the domain's TXT records and confirm whether a v=spf1 record exists.",
    references: [cweUrl(290), "https://www.rfc-editor.org/rfc/rfc7208"],
  },
  email_dkim_missing: {
    cvss: 4.3,
    cwe: cweId(290),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Tentative",
    businessImpact: "Without DKIM, outgoing mail isn't cryptographically signed, so recipients can't verify message integrity/origin.",
    attackScenario: "An attacker's spoofed message can't be distinguished from a genuine one on DKIM grounds alone.",
    verificationSteps: "Query the DKIM selector TXT record (selector is provider-specific, so absence at the default guess is not fully conclusive).",
    references: ["https://www.rfc-editor.org/rfc/rfc6376"],
  },
  email_dmarc_missing: {
    cvss: 5.3,
    cwe: cweId(290),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Confirmed",
    businessImpact: "Without DMARC, there's no policy telling receiving servers what to do with mail that fails SPF/DKIM, and no reporting visibility into spoofing attempts.",
    attackScenario: "Phishing mail spoofing this domain is more likely to reach victims' inboxes without a DMARC reject/quarantine policy.",
    verificationSteps: "Query _dmarc.<domain> TXT record and confirm policy (p=none/quarantine/reject).",
    references: [cweUrl(290), "https://www.rfc-editor.org/rfc/rfc7489"],
  },
  email_dmarc_weak_policy: {
    cvss: 3.1,
    cwe: cweId(290),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Confirmed",
    businessImpact: "A DMARC policy of p=none only reports on failures without instructing mail servers to reject/quarantine them.",
    attackScenario: "Spoofed mail still reaches inboxes even though DMARC is technically configured.",
    verificationSteps: "Query _dmarc.<domain> TXT record and inspect the p= value.",
    references: [cweUrl(290)],
  },
  email_bimi_missing: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "email",
    defaultConfidence: "Firm",
    businessImpact: "Informational — BIMI is a brand-visibility feature, not a security control, and typically requires DMARC enforcement first.",
    attackScenario: "N/A",
    verificationSteps: "Query default._bimi.<domain> TXT record.",
    references: ["https://bimigroup.org/"],
  },

  // Performance
  performance_summary: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "performance",
    defaultConfidence: "Firm",
    businessImpact: "Informational — performance metrics, not a security weakness.",
    attackScenario: "N/A",
    verificationSteps: "Re-measure with a browser devtools Network tab or a dedicated performance testing tool.",
    references: [],
  },
  performance_slow_ttfb: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "performance",
    defaultConfidence: "Firm",
    businessImpact: "Slow time-to-first-byte affects user experience and SEO, not directly security.",
    attackScenario: "N/A",
    verificationSteps: "Re-measure response time from multiple locations/times to rule out a transient network issue.",
    references: [],
  },
  performance_no_compression: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "performance",
    defaultConfidence: "Confirmed",
    businessImpact: "Missing gzip/brotli compression increases bandwidth and load time; not itself a vulnerability.",
    attackScenario: "N/A",
    verificationSteps: "Inspect the Content-Encoding response header.",
    references: [],
  },

  // CMS (WordPress)
  cms_version_disclosed: {
    cvss: 3.1,
    cwe: cweId(200),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "A disclosed CMS version lets an attacker look up known vulnerabilities for that exact version.",
    attackScenario: "An attacker checks the disclosed version against public CVE databases for a matching exploit.",
    verificationSteps: "Fetch the generator meta tag / readme.html and confirm the disclosed version string.",
    references: [cweUrl(200)],
  },
  cms_xmlrpc_exposed: {
    cvss: 5.3,
    cwe: cweId(16),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "xmlrpc.php has historically been abused for brute-force amplification (system.multicall) and DDoS pingback abuse.",
    attackScenario: "An attacker uses xmlrpc.php's multicall method to attempt many authentication guesses in a single request, or abuses pingback for amplification.",
    verificationSteps: "Request /xmlrpc.php directly and confirm it responds (this scan only confirms exposure — it never sends authentication attempts).",
    references: [cweUrl(16)],
  },
  cms_user_enum: {
    cvss: 5.3,
    cwe: cweId(200),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "server",
    defaultConfidence: "Tentative",
    businessImpact: "Enumerable usernames make targeted password-guessing or phishing easier.",
    attackScenario: "An attacker iterates ?author=1,2,3... and records the usernames each redirect reveals.",
    verificationSteps: "Request the author-archive URL pattern and confirm whether it redirects to a username-revealing permalink.",
    references: [cweUrl(200)],
  },
  cms_eol_version: {
    cvss: 7.5,
    cwe: cweId(1104),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "server",
    defaultConfidence: "Tentative",
    businessImpact: "Running an end-of-life CMS version means known vulnerabilities in it will never be patched.",
    attackScenario: "An attacker matches the disclosed version against public exploit databases for that unsupported release line.",
    verificationSteps: "Compare the disclosed version against the CMS project's current supported-release documentation.",
    references: [cweUrl(1104), OWASP_TOP10],
  },

  // Dependency findings (DependencyFinding has no `category` field — runScan.ts looks these
  // up by a synthetic key derived from `reason` instead).
  dependency_known_cve: {
    cvss: 7.5,
    cwe: cweId(1035),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "js",
    defaultConfidence: "Firm",
    businessImpact: "A dependency with a known CVE can be exploited using a public, often well-documented technique.",
    attackScenario: "An attacker identifies the exact vulnerable package/version (e.g. from a lockfile or bundle) and applies the corresponding public exploit.",
    verificationSteps: "Cross-check the reported package+version against the referenced CVE ID(s) in a public vulnerability database.",
    references: [cweUrl(1035), OWASP_TOP10],
  },
  dependency_deprecated_or_abandoned: {
    cvss: 4.0,
    cwe: cweId(1104),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "js",
    defaultConfidence: "Firm",
    businessImpact: "Deprecated/abandoned packages no longer receive security patches, so any future vulnerability in them will never be fixed upstream.",
    attackScenario: "An attacker waits for (or already knows of) a vulnerability in the abandoned package that will never be patched.",
    verificationSteps: "Confirm the package's maintenance status on its registry page or repository.",
    references: [cweUrl(1104)],
  },

  cms_plugins_detected: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational — plugin inventory, not itself a weakness. Individual plugin/version findings below carry the actual risk.",
    attackScenario: "N/A",
    verificationSteps: "Inspect the page's enqueued script/style URLs under /wp-content/plugins/.",
    references: [],
  },
  cms_plugin_version_disclosed: {
    cvss: 4.3,
    cwe: cweId(200),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "A disclosed plugin version lets an attacker check it against public vulnerability databases for that exact release.",
    attackScenario: "An attacker cross-references the plugin name+version against a public CVE/vulnerability database for a matching exploit.",
    verificationSteps: "Fetch the plugin's readme.txt and confirm the disclosed \"Stable tag\" version.",
    references: [cweUrl(200), OWASP_TOP10],
  },
  cms_theme_detected: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "server",
    defaultConfidence: "Firm",
    businessImpact: "Informational — theme inventory, not itself a weakness.",
    attackScenario: "N/A",
    verificationSteps: "Inspect the page's asset URLs under /wp-content/themes/ and the theme's style.css header.",
    references: [],
  },

  // PHP
  php_version_disclosed: {
    cvss: 3.1,
    cwe: cweId(200),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "server",
    defaultConfidence: "Confirmed",
    businessImpact: "A disclosed PHP version lets an attacker look up known vulnerabilities for that exact runtime version.",
    attackScenario: "An attacker checks the disclosed PHP version against public CVE databases for a matching exploit.",
    verificationSteps: "Inspect the X-Powered-By response header for a PHP/x.y.z value.",
    references: [cweUrl(200)],
  },
  php_eol_version: {
    cvss: 7.5,
    cwe: cweId(1104),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "server",
    defaultConfidence: "Tentative",
    businessImpact: "Running an end-of-life PHP version means known vulnerabilities in the runtime itself will never be patched.",
    attackScenario: "An attacker matches the disclosed PHP version against public exploit databases for that unsupported release line.",
    verificationSteps: "Compare the disclosed version against PHP's official supported-versions documentation.",
    references: [cweUrl(1104), OWASP_TOP10],
  },

  // JS libraries
  outdated_js_library: {
    cvss: 6.1,
    cwe: cweId(1104),
    owaspCategory: "A06:2021 – Vulnerable and Outdated Components",
    module: "js",
    defaultConfidence: "Firm",
    businessImpact: "Outdated front-end libraries can carry known, sometimes publicly exploited, XSS or prototype-pollution vulnerabilities.",
    attackScenario: "An attacker uses a public exploit for the specific outdated library version to achieve script injection in visitors' browsers.",
    verificationSteps: "Confirm the exact library version from the script URL/comment and cross-check it against the library's published CVE history.",
    references: [cweUrl(1104), OWASP_TOP10],
  },

  // Authentication
  auth_session_cookie_exposed: {
    cvss: 6.5,
    cwe: cweId(614),
    owaspCategory: "A07:2021 – Identification and Authentication Failures",
    module: "auth",
    defaultConfidence: "Confirmed",
    businessImpact: "A session-identifying cookie without Secure/HttpOnly is easier to steal, leading to account takeover.",
    attackScenario: "An attacker intercepts the cookie over an unencrypted channel or reads it via an injected script, then reuses it to impersonate the victim.",
    verificationSteps: "Inspect the Set-Cookie header for the session cookie's Secure/HttpOnly/SameSite attributes.",
    references: [cweUrl(614), OWASP_WSTG],
  },
  auth_csrf_token_missing: {
    cvss: 6.8,
    cwe: cweId(352),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "auth",
    defaultConfidence: "Tentative",
    businessImpact: "A form without a visible anti-CSRF token may allow a malicious page to submit state-changing requests on a logged-in user's behalf.",
    attackScenario: "An attacker hosts a page that auto-submits a form to this site while the victim is logged in, performing an action the victim didn't intend.",
    verificationSteps: "Inspect the form's HTML for a hidden CSRF token field; note this is a static-HTML heuristic, not confirmation the app lacks server-side CSRF checks (e.g. SameSite cookies or header-based checks).",
    references: [cweUrl(352), OWASP_WSTG],
  },
  auth_no_mfa_indicator: {
    cvss: 4.0,
    cwe: cweId(308),
    owaspCategory: "A07:2021 – Identification and Authentication Failures",
    module: "auth",
    defaultConfidence: "Tentative",
    businessImpact: "No visible multi-factor authentication option means a compromised password alone is enough to take over an account.",
    attackScenario: "An attacker who obtains a valid password (phishing, credential stuffing) logs in directly with no second factor to stop them.",
    verificationSteps: "Manually review the login page/flow for an MFA/2FA/OTP option — this heuristic only checks for keywords in the login page's HTML.",
    references: [cweUrl(308), OWASP_WSTG],
  },
  auth_no_logout_found: {
    cvss: 2.0,
    cwe: cweId(613),
    owaspCategory: "A07:2021 – Identification and Authentication Failures",
    module: "auth",
    defaultConfidence: "Tentative",
    businessImpact: "No discoverable logout mechanism can leave sessions active longer than intended, especially on shared devices.",
    attackScenario: "A user on a shared/public computer has no clear way to end their session, leaving it available to the next user of that device.",
    verificationSteps: "Manually check the authenticated area for a logout control — this heuristic only checks unauthenticated pages for a logout link.",
    references: [cweUrl(613)],
  },
  auth_login_page_detected: {
    cvss: 0,
    cwe: cweId(1059),
    owaspCategory: "N/A",
    module: "auth",
    defaultConfidence: "Firm",
    businessImpact: "Informational — confirms a login form was found at a common path.",
    attackScenario: "N/A",
    verificationSteps: "Request the path directly and confirm a password-type input is present in the form.",
    references: [],
  },

  // OWASP active/heuristic categories
  owasp_reflected_xss: {
    cvss: 6.1,
    cwe: cweId(79),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Firm",
    businessImpact: "Reflected XSS lets an attacker run script in a victim's browser in the context of this site, enabling session theft or defacement of what the victim sees.",
    attackScenario: "An attacker sends a victim a crafted link; the parameter is reflected unescaped in the response and executes in the victim's browser.",
    verificationSteps: "Request the URL with the canary value in the parameter and confirm whether it's reflected unescaped in the response body.",
    references: [cweUrl(79), OWASP_TOP10],
  },
  owasp_sql_injection_indicator: {
    cvss: 7.6,
    cwe: cweId(89),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "A database error triggered by unexpected input suggests unsanitized input reaches a SQL query, which can potentially be escalated to data exfiltration or modification.",
    attackScenario: "An attacker refines the input further (outside the scope of this safe scan) to extract or alter data via the same unsanitized parameter.",
    verificationSteps: "Manually verify with parameterized test input and confirm the error is genuinely SQL-related, not an unrelated application error.",
    references: [cweUrl(89), OWASP_TOP10],
  },
  owasp_open_redirect: {
    cvss: 4.7,
    cwe: cweId(601),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "owasp",
    defaultConfidence: "Firm",
    businessImpact: "Confirmed open redirects are actively used in phishing campaigns because the initial link points to the trusted domain.",
    attackScenario: "An attacker distributes a link to this site's own redirect endpoint, pointing the final destination at a phishing page.",
    verificationSteps: "Request the parameter with an external test URL and confirm the Location header echoes it unmodified (this scan never follows the redirect).",
    references: [cweUrl(601), OWASP_TOP10],
  },
  owasp_clickjacking: {
    cvss: 4.3,
    cwe: cweId(1021),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "owasp",
    defaultConfidence: "Confirmed",
    businessImpact: "Without frame protection, this page can be embedded in an invisible iframe on a malicious site to trick users into clicking/typing.",
    attackScenario: "An attacker overlays this site's page in a transparent iframe on top of a decoy page, tricking the victim into unintended clicks.",
    verificationSteps: "Confirm both X-Frame-Options and CSP frame-ancestors are absent from the response headers.",
    references: [cweUrl(1021), OWASP_TOP10],
  },
  owasp_dom_xss: {
    cvss: 6.1,
    cwe: cweId(79),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Client-side sinks (innerHTML, eval, document.write) fed with unsanitized data can execute attacker-controlled script entirely in the browser, without ever touching the server.",
    attackScenario: "An attacker crafts a URL fragment/parameter that flows into the sink and executes script in the victim's browser.",
    verificationSteps: "Trace the identified sink back to its data source in the source/bundle and confirm whether that source can be attacker-influenced.",
    references: [cweUrl(79), OWASP_TOP10],
  },
  owasp_ssrf_heuristic: {
    cvss: 5.0,
    cwe: cweId(918),
    owaspCategory: "A10:2021 – Server-Side Request Forgery",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "If present, SSRF can let an attacker make the server issue requests to internal-only systems, bypassing network segmentation.",
    attackScenario: "An attacker supplies an internal/cloud-metadata URL to a parameter that triggers a server-side fetch, reading data the attacker couldn't reach directly.",
    verificationSteps: "This scanner only flags URL-shaped parameters as a heuristic signal — confirming SSRF requires an out-of-band callback listener, which this scanner does not use.",
    references: [cweUrl(918), OWASP_TOP10],
  },
  owasp_xxe_heuristic: {
    cvss: 5.0,
    cwe: cweId(611),
    owaspCategory: "A05:2021 – Security Misconfiguration",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "If an endpoint parses attacker-supplied XML with external entities enabled, it can potentially read local files or make outbound requests.",
    attackScenario: "An attacker submits XML containing an external entity reference that the parser resolves, leaking file contents or triggering SSRF.",
    verificationSteps: "This scanner only flags endpoints that appear to accept XML input as a heuristic signal — confirming XXE requires sending crafted XML, which this scanner does not do.",
    references: [cweUrl(611), OWASP_TOP10],
  },
  owasp_command_injection_heuristic: {
    cvss: 5.0,
    cwe: cweId(78),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "If present, OS command injection can lead to full server compromise.",
    attackScenario: "An attacker supplies shell metacharacters to a parameter that reaches a system call, executing arbitrary commands on the server.",
    verificationSteps: "This scanner does not send command-injection payloads; confirming this class requires authenticated/manual testing with proper authorization for that specific check.",
    references: [cweUrl(78), OWASP_TOP10],
  },
  owasp_ssti_heuristic: {
    cvss: 5.0,
    cwe: cweId(1336),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Server-side template injection can escalate to remote code execution depending on the templating engine.",
    attackScenario: "An attacker supplies template syntax in a parameter that's rendered server-side, achieving code execution if the engine allows it.",
    verificationSteps: "This scanner only flags template-syntax-shaped parameters as a heuristic signal, without sending template payloads that could evaluate expressions.",
    references: [cweUrl(1336), OWASP_TOP10],
  },
  owasp_lfi_rfi_heuristic: {
    cvss: 5.0,
    cwe: cweId(22),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Local/remote file inclusion can expose sensitive files or, in the RFI case, lead to remote code execution.",
    attackScenario: "An attacker supplies a path-traversal or remote URL value to a file-shaped parameter, reading unintended files or including remote code.",
    verificationSteps: "This scanner only flags file-path-shaped parameters as a heuristic signal, without sending traversal sequences or remote URLs.",
    references: [cweUrl(22), OWASP_TOP10],
  },
  owasp_idor_heuristic: {
    cvss: 5.0,
    cwe: cweId(639),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "If present, IDOR lets a user access another user's data simply by changing an identifier in the request.",
    attackScenario: "An attacker changes a numeric ID in the URL/parameter and receives another user's record because ownership isn't re-checked server-side.",
    verificationSteps: "This scanner only flags numeric-ID-shaped parameters as a heuristic signal — confirming IDOR requires authenticated testing with two distinct accounts, which this scanner does not perform.",
    references: [cweUrl(639), OWASP_TOP10],
  },
  owasp_broken_access_control_heuristic: {
    cvss: 5.0,
    cwe: cweId(284),
    owaspCategory: "A01:2021 – Broken Access Control",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Broken access control lets a user perform actions or view data outside their intended permissions.",
    attackScenario: "An attacker accesses an admin/privileged path or function directly, without ever being granted that role.",
    verificationSteps: "This scanner only flags admin/privileged-looking paths that respond without an auth challenge as a heuristic signal — full confirmation requires authenticated testing across roles.",
    references: [cweUrl(284), OWASP_TOP10],
  },
  owasp_insecure_deserialization_heuristic: {
    cvss: 5.0,
    cwe: cweId(502),
    owaspCategory: "A08:2021 – Software and Data Integrity Failures",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Insecure deserialization of untrusted data (including unrestricted file uploads that get processed server-side) can lead to remote code execution.",
    attackScenario: "An attacker uploads or submits a crafted serialized object/file that the server deserializes or processes unsafely.",
    verificationSteps: "This scanner only flags file-upload forms as a heuristic signal — confirming this class requires authenticated testing with a controlled payload, which this scanner does not send.",
    references: [cweUrl(502), OWASP_TOP10],
  },
  owasp_stored_xss_heuristic: {
    cvss: 5.0,
    cwe: cweId(79),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "Stored XSS affects every visitor who views the page where the malicious input was saved, not just the original submitter.",
    attackScenario: "An attacker submits script through a form; it's stored and later rendered unescaped to other visitors, executing in their browsers.",
    verificationSteps: "Confirming this class requires a multi-step submit-then-view-as-another-user test, which this scanner does not perform (no submission of persistent content).",
    references: [cweUrl(79), OWASP_TOP10],
  },
  owasp_prototype_pollution_heuristic: {
    cvss: 5.0,
    cwe: cweId(1321),
    owaspCategory: "A03:2021 – Injection",
    module: "owasp",
    defaultConfidence: "Tentative",
    businessImpact: "If present, prototype pollution can lead to XSS, denial of service, or in some cases remote code execution in Node.js contexts.",
    attackScenario: "An attacker submits a crafted object with __proto__/constructor.prototype keys that pollutes shared object behavior application-wide.",
    verificationSteps: "This scanner only flags the presence of known-vulnerable JS library versions with public prototype-pollution CVEs as a heuristic signal, without sending pollution payloads.",
    references: [cweUrl(1321), OWASP_TOP10],
  },
};

export function lookupCatalog(category: string): CatalogEntry | null {
  return FINDING_CATALOG[category] ?? null;
}
