import "dotenv/config";
import { getDb } from "../src/lib/db";

// QA Testing Management module — Phase 2 (database schema). Full schema created up front so
// later phases (API, frontend) never need a follow-up ALTER migration for a missing column.
// Follows this app's existing conventions exactly (see scripts/migrate-website.ts): IDENTITY
// int PKs (no GUIDs), named FK/index constraints, no ON DELETE CASCADE (child rows are
// deleted explicitly in FK-safe order by the API layer, same as scripts/migrate-servers.ts's
// CHILD_TABLE_DELETES pattern), CreatedAt/UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME().
//
// TestCaseNumber ("TC-00042") and BugNumber/TestRunNumber are generated by the API layer at
// insert time (COUNT/MAX-based), not by the database — no existing table in this app uses a
// DB-generated formatted reference number, so this follows the established convention of
// keeping that logic in application code.
//
// This app has no "Projects/Modules/Releases" concept anywhere (confirmed by a full grep of
// every existing migration script) — QaProjects/QaModules/QaReleases are new, QA-scoped
// lookup tables, not a repurposing of anything that already existed.

async function main() {
  const db = await getDb();

  // --- Organizational lookup tables (new — nothing existing to reuse) ---

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaProjects' AND xtype='U')
    CREATE TABLE QaProjects (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      Name NVARCHAR(200) NOT NULL,
      Description NVARCHAR(1000) NULL,
      IsActive BIT NOT NULL DEFAULT 1,
      CreatedByUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    )
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaModules' AND xtype='U')
    CREATE TABLE QaModules (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      ProjectId INT NOT NULL,
      Name NVARCHAR(200) NOT NULL,
      Description NVARCHAR(1000) NULL,
      CreatedByUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaModules_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaModules_ProjectId')
    CREATE INDEX IX_QaModules_ProjectId ON QaModules (ProjectId)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaReleases' AND xtype='U')
    CREATE TABLE QaReleases (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      ProjectId INT NOT NULL,
      Name NVARCHAR(100) NOT NULL,
      ReleaseDate DATE NULL,
      Status VARCHAR(20) NOT NULL DEFAULT 'Planned',
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaReleases_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaReleases_ProjectId')
    CREATE INDEX IX_QaReleases_ProjectId ON QaReleases (ProjectId)
  `;

  // --- Test suites & cases ---

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestSuites' AND xtype='U')
    CREATE TABLE QaTestSuites (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      ProjectId INT NOT NULL,
      ModuleId INT NULL,
      Name NVARCHAR(200) NOT NULL,
      Description NVARCHAR(1000) NULL,
      Status VARCHAR(20) NOT NULL DEFAULT 'Active',
      CreatedByUserId INT NULL,
      UpdatedByUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaTestSuites_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id),
      CONSTRAINT FK_QaTestSuites_QaModules FOREIGN KEY (ModuleId) REFERENCES QaModules(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestSuites_ProjectId')
    CREATE INDEX IX_QaTestSuites_ProjectId ON QaTestSuites (ProjectId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestSuites_Status')
    CREATE INDEX IX_QaTestSuites_Status ON QaTestSuites (Status)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestCases' AND xtype='U')
    CREATE TABLE QaTestCases (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      ProjectId INT NOT NULL,
      ModuleId INT NULL,
      TestSuiteId INT NOT NULL,
      TestCaseNumber VARCHAR(20) NOT NULL UNIQUE,
      Title NVARCHAR(300) NOT NULL,
      Description NVARCHAR(MAX) NULL,
      Preconditions NVARCHAR(MAX) NULL,
      ExpectedResult NVARCHAR(MAX) NULL,
      Priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
      Severity VARCHAR(20) NULL,
      TestType VARCHAR(30) NOT NULL DEFAULT 'Functional',
      AutomationStatus VARCHAR(20) NOT NULL DEFAULT 'Manual',
      EstimatedMinutes INT NULL,
      Status VARCHAR(20) NOT NULL DEFAULT 'Draft',
      CreatedByUserId INT NULL,
      UpdatedByUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaTestCases_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id),
      CONSTRAINT FK_QaTestCases_QaModules FOREIGN KEY (ModuleId) REFERENCES QaModules(Id),
      CONSTRAINT FK_QaTestCases_QaTestSuites FOREIGN KEY (TestSuiteId) REFERENCES QaTestSuites(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestCases_TestSuiteId')
    CREATE INDEX IX_QaTestCases_TestSuiteId ON QaTestCases (TestSuiteId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestCases_Status')
    CREATE INDEX IX_QaTestCases_Status ON QaTestCases (Status)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestCases_ProjectId')
    CREATE INDEX IX_QaTestCases_ProjectId ON QaTestCases (ProjectId)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestCaseSteps' AND xtype='U')
    CREATE TABLE QaTestCaseSteps (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      TestCaseId INT NOT NULL,
      StepNumber INT NOT NULL,
      Action NVARCHAR(MAX) NOT NULL,
      TestData NVARCHAR(MAX) NULL,
      ExpectedResult NVARCHAR(MAX) NULL,
      CONSTRAINT FK_QaTestCaseSteps_QaTestCases FOREIGN KEY (TestCaseId) REFERENCES QaTestCases(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestCaseSteps_TestCaseId')
    CREATE INDEX IX_QaTestCaseSteps_TestCaseId ON QaTestCaseSteps (TestCaseId, StepNumber)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestCaseTags' AND xtype='U')
    CREATE TABLE QaTestCaseTags (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      TestCaseId INT NOT NULL,
      Tag NVARCHAR(50) NOT NULL,
      CONSTRAINT FK_QaTestCaseTags_QaTestCases FOREIGN KEY (TestCaseId) REFERENCES QaTestCases(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestCaseTags_TestCaseId')
    CREATE INDEX IX_QaTestCaseTags_TestCaseId ON QaTestCaseTags (TestCaseId)
  `;

  // --- Test runs & execution ---

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestRuns' AND xtype='U')
    CREATE TABLE QaTestRuns (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      TestRunNumber VARCHAR(20) NOT NULL UNIQUE,
      Name NVARCHAR(200) NOT NULL,
      Description NVARCHAR(1000) NULL,
      ProjectId INT NOT NULL,
      ReleaseId INT NULL,
      Environment NVARCHAR(100) NULL,
      Browser NVARCHAR(100) NULL,
      OperatingSystem NVARCHAR(100) NULL,
      Device NVARCHAR(100) NULL,
      StartDate DATE NULL,
      EndDate DATE NULL,
      Status VARCHAR(20) NOT NULL DEFAULT 'Planned',
      CreatedByUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaTestRuns_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id),
      CONSTRAINT FK_QaTestRuns_QaReleases FOREIGN KEY (ReleaseId) REFERENCES QaReleases(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestRuns_ProjectId')
    CREATE INDEX IX_QaTestRuns_ProjectId ON QaTestRuns (ProjectId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestRuns_Status')
    CREATE INDEX IX_QaTestRuns_Status ON QaTestRuns (Status)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestRunCases' AND xtype='U')
    CREATE TABLE QaTestRunCases (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      TestRunId INT NOT NULL,
      TestCaseId INT NOT NULL,
      AssignedUserId INT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaTestRunCases_QaTestRuns FOREIGN KEY (TestRunId) REFERENCES QaTestRuns(Id),
      CONSTRAINT FK_QaTestRunCases_QaTestCases FOREIGN KEY (TestCaseId) REFERENCES QaTestCases(Id),
      CONSTRAINT UQ_QaTestRunCases_Run_Case UNIQUE (TestRunId, TestCaseId)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestRunCases_TestRunId')
    CREATE INDEX IX_QaTestRunCases_TestRunId ON QaTestRunCases (TestRunId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestRunCases_AssignedUserId')
    CREATE INDEX IX_QaTestRunCases_AssignedUserId ON QaTestRunCases (AssignedUserId)
  `;

  // One row per execution ATTEMPT (never overwritten) — this is what "previous execution
  // result" and "execution history" both read from: the latest row per TestRunCaseId is the
  // current result, older rows are history.
  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaTestExecutions' AND xtype='U')
    CREATE TABLE QaTestExecutions (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      TestRunCaseId INT NOT NULL,
      Result VARCHAR(20) NOT NULL,
      ActualResult NVARCHAR(MAX) NULL,
      Notes NVARCHAR(MAX) NULL,
      DurationMinutes INT NULL,
      Browser NVARCHAR(100) NULL,
      Device NVARCHAR(100) NULL,
      OperatingSystem NVARCHAR(100) NULL,
      AppVersion NVARCHAR(50) NULL,
      ExecutedByUserId INT NULL,
      ExecutedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      CONSTRAINT FK_QaTestExecutions_QaTestRunCases FOREIGN KEY (TestRunCaseId) REFERENCES QaTestRunCases(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaTestExecutions_TestRunCaseId_ExecutedAt')
    CREATE INDEX IX_QaTestExecutions_TestRunCaseId_ExecutedAt ON QaTestExecutions (TestRunCaseId, ExecutedAt DESC)
  `;

  // --- Bugs ---

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaBugs' AND xtype='U')
    CREATE TABLE QaBugs (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      BugNumber VARCHAR(20) NOT NULL UNIQUE,
      Title NVARCHAR(300) NOT NULL,
      Description NVARCHAR(MAX) NULL,
      ProjectId INT NOT NULL,
      TestCaseId INT NULL,
      TestExecutionId INT NULL,
      TestRunId INT NULL,
      StepsToReproduce NVARCHAR(MAX) NULL,
      ExpectedResult NVARCHAR(MAX) NULL,
      ActualResult NVARCHAR(MAX) NULL,
      Severity VARCHAR(20) NOT NULL DEFAULT 'Medium',
      Priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
      Status VARCHAR(20) NOT NULL DEFAULT 'New',
      AssignedDeveloperUserId INT NULL,
      ReporterUserId INT NULL,
      Environment NVARCHAR(100) NULL,
      Browser NVARCHAR(100) NULL,
      Device NVARCHAR(100) NULL,
      AppVersion NVARCHAR(50) NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
      ResolvedAt DATETIME2 NULL,
      CONSTRAINT FK_QaBugs_QaProjects FOREIGN KEY (ProjectId) REFERENCES QaProjects(Id),
      CONSTRAINT FK_QaBugs_QaTestCases FOREIGN KEY (TestCaseId) REFERENCES QaTestCases(Id),
      CONSTRAINT FK_QaBugs_QaTestExecutions FOREIGN KEY (TestExecutionId) REFERENCES QaTestExecutions(Id),
      CONSTRAINT FK_QaBugs_QaTestRuns FOREIGN KEY (TestRunId) REFERENCES QaTestRuns(Id)
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaBugs_Status')
    CREATE INDEX IX_QaBugs_Status ON QaBugs (Status)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaBugs_ProjectId')
    CREATE INDEX IX_QaBugs_ProjectId ON QaBugs (ProjectId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaBugs_AssignedDeveloperUserId')
    CREATE INDEX IX_QaBugs_AssignedDeveloperUserId ON QaBugs (AssignedDeveloperUserId)
  `;

  // --- Attachments, comments, activity log ---
  // EntityType/EntityId is a deliberate polymorphic soft-reference (TestCase/TestExecution/
  // Bug share one attachments/comments table) — no FK, matching this app's existing
  // soft-reference convention for cross-cutting columns (e.g. *ByUserId columns elsewhere
  // are plain INT without a declared FK).

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaAttachments' AND xtype='U')
    CREATE TABLE QaAttachments (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      EntityType VARCHAR(30) NOT NULL,
      EntityId INT NOT NULL,
      FilePath NVARCHAR(500) NOT NULL,
      OriginalFileName NVARCHAR(300) NOT NULL,
      ContentType NVARCHAR(100) NULL,
      SizeBytes INT NOT NULL,
      UploadedByUserId INT NULL,
      UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaAttachments_Entity')
    CREATE INDEX IX_QaAttachments_Entity ON QaAttachments (EntityType, EntityId)
  `;

  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaComments' AND xtype='U')
    CREATE TABLE QaComments (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      EntityType VARCHAR(30) NOT NULL,
      EntityId INT NOT NULL,
      AuthorUserId INT NULL,
      Message NVARCHAR(MAX) NOT NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaComments_Entity')
    CREATE INDEX IX_QaComments_Entity ON QaComments (EntityType, EntityId)
  `;

  // QA-specific detail audit trail (in addition to, not instead of, the app's existing
  // generic AdminAuditLog / logAdminAction() — the module calls both: logAdminAction() for
  // the coarse "what happened" trail every other module writes to, and this table for the
  // richer before/after-value detail the spec's audit requirements ask for).
  await db.query`
    IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='QaActivityLogs' AND xtype='U')
    CREATE TABLE QaActivityLogs (
      Id INT IDENTITY(1,1) PRIMARY KEY,
      EntityType VARCHAR(30) NOT NULL,
      EntityId INT NOT NULL,
      Action VARCHAR(50) NOT NULL,
      PreviousValue NVARCHAR(MAX) NULL,
      NewValue NVARCHAR(MAX) NULL,
      UserId INT NULL,
      IpAddress VARCHAR(64) NULL,
      CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    )
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaActivityLogs_Entity')
    CREATE INDEX IX_QaActivityLogs_Entity ON QaActivityLogs (EntityType, EntityId)
  `;
  await db.query`
    IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_QaActivityLogs_CreatedAt')
    CREATE INDEX IX_QaActivityLogs_CreatedAt ON QaActivityLogs (CreatedAt DESC)
  `;

  console.log("QA Testing Management tables ready (15 tables).");

  // --- Seed roles + default permission grants ---
  // Admin is NOT seeded here — requireQaPermission() (Phase 3) special-cases role === "Admin"
  // to always pass, same superuser convention requireAdmin() already uses everywhere else in
  // this app, so Admin never needs explicit RolePermissions rows.

  const newRoles: { name: string; description: string }[] = [
    { name: "QA Manager", description: "Manages QA test suites, test cases, test runs, bugs and reports." },
    { name: "Tester", description: "Views and executes assigned test cases; can file and retest bugs." },
    { name: "Developer", description: "Views failed tests and bugs assigned to them." },
    { name: "Viewer", description: "Read-only access to QA test cases and reports." },
  ];

  for (const role of newRoles) {
    const existing = await db.query<{ Cnt: number }>`SELECT COUNT(*) AS Cnt FROM Roles WHERE Name = ${role.name}`;
    if (existing.recordset[0].Cnt === 0) {
      await db.query`INSERT INTO Roles (Name, Description, IsSystem) VALUES (${role.name}, ${role.description}, 0)`;
      console.log(`Seeded role: ${role.name}`);
    }
  }

  const QA_PERMISSION_KEYS = [
    "qa_view", "qa_create", "qa_edit", "qa_delete", "qa_execute",
    "qa_manage_runs", "qa_manage_bugs", "qa_view_reports", "qa_admin",
  ];

  const defaultGrants: Record<string, string[]> = {
    "QA Manager": ["qa_view", "qa_create", "qa_edit", "qa_delete", "qa_execute", "qa_manage_runs", "qa_manage_bugs", "qa_view_reports"],
    "Tester": ["qa_view", "qa_execute", "qa_manage_bugs"],
    "Developer": ["qa_view", "qa_manage_bugs"],
    "Viewer": ["qa_view", "qa_view_reports"],
  };

  for (const [roleName, grantedKeys] of Object.entries(defaultGrants)) {
    const roleRow = await db.query<{ Id: number }>`SELECT Id FROM Roles WHERE Name = ${roleName}`;
    const roleId = roleRow.recordset[0]?.Id;
    if (!roleId) continue;

    for (const key of QA_PERMISSION_KEYS) {
      const allowed = grantedKeys.includes(key);
      const existing = await db.query<{ Cnt: number }>`
        SELECT COUNT(*) AS Cnt FROM RolePermissions WHERE RoleId = ${roleId} AND PermissionKey = ${key}
      `;
      if (existing.recordset[0].Cnt === 0) {
        await db.query`INSERT INTO RolePermissions (RoleId, PermissionKey, Allowed) VALUES (${roleId}, ${key}, ${allowed})`;
      }
    }
  }
  console.log("Seeded default RolePermissions grants for QA Manager, Tester, Developer, Viewer.");

  console.log("QA Testing Management migration complete (Phase 2 of 6).");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
